export const background: string;
export const sky: string;
export const desert: string;
export const sun: string;
export const cactus: string;
export const stalk: string;
export const arm: string;
export const right: string;
export const branch: string;
